name: VindicterraStaffUtils
Author: Frostwolf74
version: '1.0-SNAPSHOT'
main: me.frostwolf74.vindicterraStaffUtils.VindicterraStaffUtils
api-version: '1.20'

commands:
  # utils
  staff:
    description: Toggles staff mode
    usage: /staff [player]
    permission: VSU.staff
    aliases:
      - sm

  staffchat:
    description: Toggles staff chat mode or sends a message in staff chat
    usage: /staffchat
    permission: VSU.staffchat
    aliases:
      - sc

  freeze:
    description: Freeze player's movement, rotation and disable interactions
    usage: /freeze <player>
    permission: VSU.freeze

  inventorysee:
    description: View a player's inventory
    usage: /inventorysee <player>
    permission: VSU.inventorysee
    aliases:
      - invsee

  vanish:
    description: Vanish yourself or another player
    usage: /vanish [player]
    permission: VSU.vanish
    aliases:
      - v

  # punishments

  mute:
    description: Prevents a player from sending public chat messages
    usage: /mute <player> <length<h/d/w/m/y>>
    permission: VSU.punish.mute

  unmute:
    description: Lift a mute on a player
    usage: /unmute <player> [reason]
    permission: VSU.punish.unmute

  kick:
    description: Kicks a player from the server
    usage: /kick <player> <length<h/d/w/m/y>>
    permission: VSU.punish.kick

  ban:
    description: Bans a player from the server
    usage: /ban <player> <length<h/d/w/m/y>>
    permission: VSU.punish.ban

  unban:
    description: Lifts a player ban
    usage: /unban <player> [reason]
    permission: VSU.punish.unban

permissions:
  VSU:
    children:
      VSU.staff:
        default: false
      VSU.staffchat:
        default: false
      VSU.freeze:
        default: false
      VSU.inventorysee:
        default: false
      VSU.rtp:
        default: false
      VSU.nightvision:
        default: false
      VSU.vanish:
        default: false
      VSU.onlineplayer:
        default: false
      VSU.punish.mute:
        default: false
      VSU.punish.unmute:
        default: false
      VSU.punish.kick:
        default: false
      VSU.punish.ban:
        default: false